spring:
  datasource:
    username: root
    password: '{cipher}574d82cae292c839b89b781ac4206260cea181abff47bac463b0d052496663e8'
    
  jpa:
      show-sql: true
      hibernate:
          ddl-auto: update
        
      properties:
        hibernate:
            dialect: org.hibernate.dialect.MySQL5Dialect
  zipkin:
    base-url: http://localhost:5005/

  sleuth:
    sampler:
      probability: 1.0

 
logging:
  file: Errorlog.log
  level:
    root: info
    com.infoys.sim: info
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss,SSS} %5p [%t] %c [%M] - %m%n"

eureka:
    client:
        service-url.defaultZone: http://127.0.0.1:2222/eureka/
        
security:
  oauth2:
    client:
      accessTokenUri: https://github.com/login/oauth/access_token
      userAuthorizationUri: https://github.com/login/oauth/authorize
    resource:
      userInfoUri: https://api.github.com/user 
